# Generated by Django 5.0.2 on 2024-03-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_comment_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sentiment',
            field=models.CharField(choices=[('Positive', 'positive'), ('Negative', 'negative')], default='Positive', max_length=10),
            preserve_default=False,
        ),
    ]
